apiVersion: apps/v1
kind: Deployment
metadata:
  name: gymapi-be1
  labels:
    app: gymapi-be1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gymapi-be1
  template:
    metadata:
      labels:
        app: gymapi-be1
    spec:
      containers:
      - name: gymapi-be1
        image: rafdev0904/gym:153
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: gymapi-svc
spec:
  selector:
    app: gymapi-be1
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
    nodePort: 31112
